apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: "2019-08-09T07:25:59Z"
  generation: 1
  labels:
    run: example
  name: example
  namespace: default
  resourceVersion: "365497"
  selfLink: /apis/apps/v1/namespaces/default/deployments/example
  uid: ef1a38e9-ba76-11e9-8458-525400261060
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: example
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: example
    spec:
      containers:
      - image: nginx:1.13.5-alpine
        imagePullPolicy: IfNotPresent
        name: example
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
