apiVersion: v1
kind: Pod                                            # 1
metadata:
  name: helloworld                                   # 2
  namespace: finance
  labels:                                            
    app: helloworld
spec:                                                # 3
  containers:
    - image: gvelrajan/helloworld:v2.0              # 4
      imagePullPolicy: Always
      name: helloworld                               # 5
      ports:
        - containerPort: 80                          # 6
