kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: finance 
  name: finance-reader
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods", "services", "nodes"]
  verbs: ["get", "watch", "list"]
