apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginxru
spec:
  replicas: 10
  selector:
    matchLabels:
      service: http-server
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        service: http-server
    spec:
      containers:
      - name: nginxru
        image: nginx:1.11.5
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
