apiVersion: v1
kind: Pod
metadata:
  annotations:
    cni.projectcalico.org/podIP: 192.168.2.72/32
  creationTimestamp: "2019-08-15T17:32:52Z"
  generateName: hello-world-5dd96f4758-
  labels:
    pod-template-hash: 5dd96f4758
    run: hello-world
  name: hello-world-5dd96f4758-5lh9v
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: hello-world-5dd96f4758
    uid: 4f9b3c3e-bf82-11e9-b614-525400261060
  resourceVersion: "599299"
  selfLink: /api/v1/namespaces/default/pods/hello-world-5dd96f4758-5lh9v
  uid: b5843c4c-bf82-11e9-b614-525400261060
spec:
  containers:
  - image: gcr.io/google-samples/hello-app:1.0
    imagePullPolicy: IfNotPresent
    name: hello-world
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-pdxr5
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: c1-node2
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: default-token-pdxr5
    secret:
      defaultMode: 420
      secretName: default-token-pdxr5
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2019-08-15T17:32:52Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2019-08-15T17:32:54Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2019-08-15T17:32:54Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2019-08-15T17:32:52Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://4766a71cebeb981a3b03fd3531df7b4caf879995e8072a27fc4cbb45658be647
    image: gcr.io/google-samples/hello-app:1.0
    imageID: docker-pullable://gcr.io/google-samples/hello-app@sha256:c62ead5b8c15c231f9e786250b07909daf6c266d0fcddd93fea882eb722c3be4
    lastState: {}
    name: hello-world
    ready: true
    restartCount: 0
    state:
      running:
        startedAt: "2019-08-15T17:32:53Z"
  hostIP: 172.20.50.22
  phase: Running
  podIP: 192.168.2.72
  qosClass: BestEffort
  startTime: "2019-08-15T17:32:52Z"
